CREATE DATABASE DBCUBEX;

USE DBCUBEX;

CREATE TABLE TIENDA (
    COD_T INT ,
    NAME_T VARCHAR(30) NOT NULL,
    CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    MUNICIPIO VARCHAR(30),
    NUM_EXT INT,
    NUM_INT INT,
    CP INT,
    TELEFONO VARCHAR(10),
    CONSTRAINT PK_TIENDA PRIMARY KEY (COD_T)
);
CREATE TABLE PROVEEDOR(
    COD_PV INT,
    NOMBRES_PV VARCHAR(20) NOT NULL,
    APP_PV VARCHAR(20) NOT NULL,
    APM_PV VARCHAR(20) NOT NULL,
    CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    MUNICIPIO VARCHAR(30),
    NUM_EXT INT,
    NUM_INT INT,
    CP INT,
    TELEFONO_PV VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (COD_PV)
);
CREATE TABLE PRODUCTOS_OFERTA(
    C_BARRAS_OF INT, 
    COD_PV INT NOT NULL,
    PRODUCTO_OF VARCHAR(30) NOT NULL,
    CONSTRAINT PK_PRODUCTOS_OFERTA PRIMARY KEY (C_BARRAS_OF),
    CONSTRAINT FK_COD_PV_01 FOREIGN KEY (COD_PV) REFERENCES PROVEEDOR(COD_PV)
);
CREATE TABLE PROVEE(
    REFERENCIA VARCHAR(10), 
    MontoMAx INT,
    FECHA DATETIME,
    COD_PV INT NOT NULL,
    COD_T INT NOT NULL,
    CONSTRAINT PK_PROVEE PRIMARY KEY (REFERENCIA, COD_PV, COD_T),
    CONSTRAINT FK_COD_PV_02 FOREIGN KEY (COD_PV) REFERENCES PROVEEDOR (COD_PV),
    CONSTRAINT FK_COD_T_02 FOREIGN KEY (COD_T) REFERENCES TIENDA(COD_T)
);

CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT AUTO_INCREMENT,
    NOMBRES_EM VARCHAR(30) NOT NULL,
    APP_EM VARCHAR(20) NOT NULL,
    APM_EM VARCHAR(20) NOT NULL,
    CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    MUNICIPIO VARCHAR(30),
    NUM_EXT INT,
    NUM_INT INT,
    CP INT,
    TELEFONO_EM VARCHAR(10) NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY(ID_EMPLEADO)
);
CREATE TABLE CLIENTE(
    ID_CLIENTE INT ,
    NOMBRES_CL VARCHAR(30)NOT NULL,
    APP_CL VARCHAR(20) NOT NULL,
    APM_CL VARCHAR(20) NOT NULL,
    CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    MUNICIPIO VARCHAR(30),
    NUM_EXT INT,
    NUM_INT INT,
    CP INT,
    TELEFONOM_CL VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);
CREATE TABLE CARGOS(
    ID_CARGO INT, 
    CARGO VARCHAR(15) DEFAULT 'VENDEDOR' NOT NULL,
    CONSTRAINT PK_CARGOS PRIMARY KEY (ID_CARGO)
);
CREATE TABLE EMPLEADOS_CARGO(
    ID_EMPLEADO INT,
    ID_CARGO INT,
    CONSTRAINT PK_EMPELADOS_CARGO PRIMARY KEY (ID_EMPLEADO, ID_CARGO),
    CONSTRAINT FK_EMPLEADO_01 FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    CONSTRAINT FK_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGOS (ID_CARGO)
);

CREATE TABLE PRODUCTO(
    C_BARRAS INT, 
    NOMBRE_P VARCHAR(30) NOT NULL,
    STOCK INT,
    STOCK_MIN INT,
    PRECIO_N DECIMAL(4,2),
    PRECIO_V DECIMAL(4,2),
    COD_T INT NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(C_BARRAS),
    CONSTRAINT FK_COD_T_01 FOREIGN KEY (COD_T) REFERENCES TIENDA(COD_T),
    CONSTRAINT CK_EN_EXISTENCIA CHECK ( STOCK > 0 AND STOCK< STOCK_MIN )
);

CREATE TABLE METODO_PAGO(
    ID_METODO INT,
    METODO VARCHAR(10) NOT NULL,
    CONSTRAINT PK_METODO_PAGO PRIMARY KEY (ID_METODO)
);

CREATE TABLE TIPO_VENTA(
    ID_TIPO_VENTA INT,
    TIPOVENTA VARCHAR(10) NOT NULL,
    CONSTRAINT PK_TIPO_VENTA PRIMARY KEY (ID_TIPO_VENTA)
);
CREATE TABLE VENTA(
    N_VENTA INT, 
    ID_EMPLEADO INT,
    NOMBRE_CL VARCHAR(40) DEFAULT 'DESCONOCIDO' NOT NULL,
    ID_METODO_PAGO INT,
    ID_TIPO_VENTA INT,
    FECHA_VENTA DATETIME,
    CONSTRAINT PK_VENTA PRIMARY KEY (N_VENTA),
    CONSTRAINT FK_ID_EMPLEADO_01 FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    CONSTRAINT FK_ID_METODO_PAGO_01 FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO),
    CONSTRAINT FK_ID_TIPO_VENTA_01 FOREIGN KEY (ID_TIPO_VENTA) REFERENCES TIPO_VENTA(ID_TIPO_VENTA)
);
CREATE TABLE PRODUCTOS_VENDIDOS(
    C_BARRAS INT,
    N_VENTA INT,
    N_PR INT,
    CONSTRAINT PK_PR_VENTA PRIMARY KEY (C_BARRAS, N_VENTA),
    CONSTRAINT FK_C_BARRAS_01 FOREIGN KEY (C_BARRAS) REFERENCES PRODUCTO (C_BARRAS),
    CONSTRAINT FK_N_VENTA_01 FOREIGN KEY (N_VENTA) REFERENCES VENTA(N_VENTA)
);
CREATE TABLE GENERIC_CARRO()
    C_BARRAS INT,
    N_PR INT,
    N_VENTA INT,
    CONSTRAINT PK_PR_VENTA PRIMARY KEY (C_BARRAS)
);
CREATE TABLE FACTURA(
    N_FACTURA INT,
    N_VENTA INT,
    NOMBRES VARCHAR(30) NOT NULL,
    APP VARCHAR(30) NOT NULL,
    APM VARCHAR(30) NOT NULL,
    RFC VARCHAR(30) NOT NULL,
    FECHA DATE,
    CALLE VARCHAR(30),
    COLONIA VARCHAR(30),
    MUNICIPIO VARCHAR(30),
    NUM_EXT INT,
    NUM_INT INT,
    CP INT,
    CONSTRAINT PK_FACTURA PRIMARY KEY (N_FACTURA),
    CONSTRAINT FK_N_VENTA_02 FOREIGN KEY (N_VENTA) REFERENCES VENTA (N_VENTA)
);


CREATE VIEW PRODUCTOS_EXISTENCIA (PRODUCTO, CANTIDAD_DISPONIBLE) AS SELECT NOMBRE_P, STOCK FROM PRODUCTO WHERE STOCK > 10 WITH CHECK OPTION;

CREATE VIEW PROVEEDORES_PRODUCTO (PRODUCTO, PROVEEDOR ) AS SELECT b.PRODUCTO_OF, a.NOMBRES_PV 
FROM PROVEEDOR a, PRODUCTOS_OFERTA b, PRODUCTO c WHERE b.C_BARRAS_OF=c.C_BARRAS;

--CREATE VIEW PRODUCTO_CARRO (PRODUCTO, CANTIDAD, PRECIO , PRECIO_VENTA) AS SELECT a.NOMBRE_P, b.N_PR,  a.PRECIO_V , b.N_PR * a.PRECIO_V FROM PRODUCTO a, GENERIC_CARRO b WHERE a.C_BARRAS=b.C_BARRAS AND b.N_VENTA= 980492;